tabPredictions <- function(){
    tabPanel(
        "Predictions", 
        icon = icon("arrow-trend-up"),
        column(width = 3,
               inputPanel(
                   sliderInput("predictions_age",
                               "Age (months)",
                               min = 0,
                               max = ceiling(max(participants$age)) + ceiling(max(participants$age)) %% 10,
                               step = 1,
                               value = c(0, ceiling(max(participants$age)) + ceiling(max(participants$age)) %% 10),
                               sep = ",",
                               dragRange = TRUE),
                   selectInput("predictions_lp",
                               "Language profile",
                               choices = c("Monolingual", "Bilingual"),
                               selected = c("Monolingual", "Bilingual"),
                               multiple = TRUE),
                   selectInput("predictions_dominance",
                               "Dominance",
                               choices = c("L1", "L2"),
                               selected = c("L1", "L2"),
                               multiple = TRUE),
                   selectInput("predictions_category",
                               "Modality",
                               choices = c("Understands", "Understands and Says"),
                               selected = c("Understands", "Understands and Says"),
                               multiple = TRUE),
                   selectInput("predictions_summary",
                               "Summary",
                               choices = c("none", "mean", "median"),
                               selected = "mean",
                               multiple = FALSE),
                   checkboxInput("predictions_uncertainty",
                                 "Show uncertainty?",
                                 value = TRUE)
               )),
        column(
            width = 9,
            tabsetPanel(
                type = "tabs",
                tabPanel("Population-level", icon = icon("globe"),
                         sliderInput("trajectories_ndraws",
                                     "Number of posterior draws",
                                     min = 1,
                                     max = nrow(collect(distinct(predictions, .draw))),
                                     value = nrow(collect(distinct(predictions, .draw)))/2,
                                     sep = ",",
                                     step = 1),
                         plotOutput("trajectories_plot")),
                tabPanel("Word-level", icon = icon("font"),
                         br(),
                         column(width = 6,
                                selectInput("trajectories_te_te",
                                            "Word",
                                            choices = te_labels,
                                            selected = 389,
                                            multiple = FALSE)
                         ),
                         column(width = 6,
                                sliderInput("trajectories_te_ndraws",
                                            "Number of posterior draws",
                                            min = 1,
                                            max = nrow(collect(distinct(predictions_te, .draw))),
                                            value = nrow(collect(distinct(predictions_te, .draw)))/2,
                                            sep = ",",
                                            step = 1)
                         ),
                         br(),
                         plotOutput("trajectories_plot_te")),
                tabPanel("Child-level", icon = icon("child"),
                         br(),
                         selectInput("trajectories_id_id",
                                     "Child",
                                     choices = collect(distinct(responses, id))$id,
                                     selected = collect(distinct(responses, id))$id[1],
                                     multiple = FALSE),
                         sliderInput("trajectories_id_ndraws",
                                     "Number of posterior draws",
                                     min = 1,
                                     max = nrow(collect(distinct(predictions_id, .draw))),
                                     value = nrow(collect(distinct(predictions_id, .draw)))/2,
                                     sep = ",",
                                     step = 1),
                         br(),
                         plotOutput("trajectories_plot_id")
                )
            )
        )
    )
}