tabItems <- function(){
    tabPanel(
        "Items", 
        icon = icon("list"),
        column(width = 2,
               inputPanel(
                   selectInput("items_class",
                               "Class",
                               choices = unique(items$class),
                               selected = unique(items$class),
                               multiple = TRUE),
                   selectInput("items_semantic_category",
                               "Semantic Category",
                               choices = unique(items$semantic_category),
                               selected = unique(items$semantic_category),
                               multiple = TRUE, width = "700px"),
                   sliderInput("items_n_syll",
                               "Syllables",
                               min = min(items$n_syll),
                               max = max(items$n_syll),
                               step = 1,
                               ticks = FALSE,
                               value = range(items$n_syll)),
                   sliderInput("items_n_phon",
                               "Phonemes",
                               min = min(items$n_phon),
                               max = max(items$n_phon),
                               step = 1,
                               value = range(items$n_phon)),
                   sliderInput("items_lv",
                               "Levenshtein",
                               min = min(items$lv),
                               max = max(items$lv),
                               step = 0.1,
                               value = range(items$lv))
               )),
        column(width = 8,
               fluidRow(
                   tabsetPanel(
                       type = "tabs",
                       tabPanel("Syllables", icon = icon("ruler-horizontal"),
                                plotOutput("items_plot_n_syll",
                                           width = 1200, 
                                           height = 300)),
                       tabPanel("Phonemes", icon = icon("ruler-horizontal"),
                                plotOutput("items_plot_n_phon",
                                           width = 1200, 
                                           height = 300)),
                       tabPanel("Class", icon = icon("language"),
                                plotOutput("items_plot_class",
                                           width = 1200, 
                                           height = 300)),
                       tabPanel("Cognateness", icon = icon("arrows-left-right"),
                                plotOutput("items_plot_lv",
                                           width = 1200, 
                                           height = 300)),
                       tabPanel("Semantic category", icon = icon("dog"),
                                plotOutput("items_plot_semantic_category",
                                           width = 1200, 
                                           height = 300))
                   )),
               fluidRow(DTOutput("items_table"))
        )
    )
}