#' Specify and sample a brms model
#' @param name A character string indicating the name to be assigned to the model
#' @param ... Arguments to be passed to [brms::brm()]
fit_model <- function(name, is_prior = FALSE, ...) {
    file_path <- ifelse(is_prior,
                        glue("results/fits/{name}_prior.rds"),
                        glue("results/fits/{name}.rds"))
    
    # we run the model in the background as an RStudio job to keep the console free
    # see R/utils.R
    fit <- brm(...,
               iter = 1000,
               cores = 4,
               chains = 4,
               init = 0.5,
               seed = 888,
               backend = "cmdstanr",
               file = file_path,
               file_refit = "never",
               control = list(adapt_delta = 0.9,
                              max_treedepth = 15),
               save_model = glue("stan/{name}.stan"))
    
    return(fit)
}

#' Extract posterior draws of fixed effect coefficients from brmsfit model via [tidybayes::gather_draws()].
#' 
#' @param model A brmsfit object
#' @param data Dataset of responses as generated by the [get_responses] function
#' @param ... Arguments to be passed to [tidybayes::gather_draws()]
get_posterior_draws <- function(model, data, ...) {
    # tidy predictor names
    str_repl <- c(
        "b_Intercept[1]" = "Comprehension and Production",
        "b_Intercept[2]" = "Comprehension",
        "b_age_std" = glue("Age (+1 SD, {round(sd(data$age, na.rm = TRUE), 2)} months)"),
        "b_lp1" = "Group (Monolingual vs. Bilingual)",
        "b_dominance1" = "Dominance (L1 vs. L2)",
        "b_lp1:dominance1" = "Group \u00d7 Dominance"
    )
    
    # posterior draws
    posterior <- gather_draws(model, `b_.*`, regex = TRUE) |>
        mutate(
            .variable_name = factor(.variable,
                                    levels = names(str_repl),
                                    labels = str_repl) |>
                as.character(),
            type = ifelse(
                str_detect(.variable, "Intercept"),
                "Intercepts (at 22 months)",
                "Slopes"
            ),
            parameter = ifelse(
                str_detect(.variable, "Intercept"),
                str_remove_all(.variable, "Intercept \\(|\\)"),
                .variable
            )
        ) |>
        select(variable = .variable, .variable_name, .type = type, 
               .chain, .iteration, .draw, .value) |>
        ungroup()
    
    # export draws
    save_files(posterior, folder = "results/posterior")
    write_dataset(posterior, 
                  path = "bvq-app/data/posterior",
                  format = "parquet",
                  partitioning = "variable")
    
    return(posterior)
}






